### PR TITLE
add nix env

### PR DESCRIPTION
**Pull request by GTrunSec**
- The upstream of https://github.com/hasktorch/hasktorch has a recursion problem.
- [TODO]using haskell.nix instead?
- [TODO] packing openmemex to appimage
- what do you like to replace the Makefile with justfile?

### CODE REVIEW

**Comment by GTrunSec** [comment]
@junjihashimoto 

I have no idea how to solve it,  any information for that?
image

**Comment by junjihashimoto** [comment]
@GTrunSec 
The version of libtorch that libtorch-ffi expects is different from the actual version of libtorch.

**Comment by junjihashimoto** [comment]
https://github.com/pytorch/pytorch/pull/58248
It has changed to ORT instead of MSNPU.

**Comment by junjihashimoto** [comment]
Is it better to use libtorch-1.9? If so, try "github:hasktorch/libtorch-nix?rev=62d80e76a02e2dc5670d128eb4375454ad3db43a" with flake.

**Comment by GTrunSec** [comment]
> Is it better to use libtorch-1.9? If so, try "github:hasktorch/libtorch-nix?rev=62d80e76a02e2dc5670d128eb4375454ad3db43a" with flake.


I'm not sure that better or not, just to be consistent with lock. A lot of compiling would be a disaster without cache.

**Pull request closed without merging**
